### ISSUE TITLE
Suggestion: Search by tags

### ISSUE THREAD

**Issue by ANoble1980** [frctl/fractalite#1]
Hi there,

Thanks for working on this prototype. I work on a 5-person UX team that is developing and maintaining a design system for our company. We use fractal currently, with some custom code for searching document titles. We saw that you've got Component Search on your list, and are super excited to see this functionality, and wanted to share a specific issue we had that might be worth addressing.

Because our documentation is intended for people new to our company as well as people who have been here a long time, but are just getting familiar with the system, we have encountered quite a few situations where people will know a slightly different name for a component than the one used in our system. For example: our applications use a lot of tabular data, but our term for these displays is "datagrid." If a brand-new team member comes to familiarize themselves with our documentation, they might search for"table," and get no results, as our search just scans title fields. I tried hiding strings, etc as a workaround, but our current implementation is just too narrow. So it'd be great if there were some way to have components show up for multiple "aliases" in the search without having to include something like "AKA ____" in the title, perhaps via a tag attribute or something.

All the best,
Adam

**Comment by allmarkedup** [comment]
Hey @ANoble1980 many thanks for the feedback - That would definitely be a great addition and I'll make sure that is a part of the search implementation. Ideally plugins would be able to configure/add more fields or values to search for and given the new architecture this should be very do-able.

I'll keep this open and post an update when anything around this gets implemented.

**Comment by allmarkedup** [comment]
Hey @ANoble1980 - I just wanted to let you know that I've now pushed a first-pass attempt at the component search functionality. It matches labels by default, but you can add a `search.aliases` property in config files to specify a list of additional strings to match (see the [button config file](https://github.com/frctl/fractalite/blob/master/demos/nunjucks/src/components/01-units/%40button/button.config.js#L55) for an example).

The search UI is likely to still go through a few iterations but I think this should address your requirements described above. If you get a chance to play with it and have any comments or suggestions then just let me know :-)
