### ISSUE TITLE
Feature request: Make component name link to first scenario 

### ISSUE THREAD

**Issue by allmarkedup** [frctl/fractalite#19]
As suggested in #14 clicking on the component name should go to the defaut scenario preview as well as the current behaviour of toggling the list of 'child' scenarios in the nav.

**Comment by allmarkedup** [comment]
Hi @ajilderda I've just pushed an update to implement this behaviour - let me know what you think if you get a chance to try it out :-)

**Comment by andrejilderda** [comment]
Hi @allmarkedup, thanks for adding this! A big improvement if you ask me. 

One thing though. I didn't notice before that a dropdown is also added when there is just one scenario. This is different from v1 and quickly clutters the navigation tree.
